// SPDX-License-Identifier: AGPL-3.0-or-later

use super::{WebFeature, wf};

pub(super) const FEATURES: &[WebFeature] = &[
    wf(
        "analysis",
        "Alerts",
        "Check alerts",
        "kaizen_alerts_check",
        &[],
        false,
        "cards",
    ),
    wf(
        "analysis",
        "Cases",
        "Archive case",
        "kaizen_cases_archive",
        &["id"],
        true,
        "toast",
    ),
    wf(
        "analysis",
        "Cases",
        "Create case",
        "kaizen_cases_create",
        &["session_id", "reason"],
        true,
        "cards",
    ),
    wf(
        "analysis",
        "Cases",
        "List cases",
        "kaizen_cases_list",
        &[],
        false,
        "table",
    ),
    wf(
        "analysis",
        "Cases",
        "Mine cases",
        "kaizen_cases_mine",
        &[],
        true,
        "cards",
    ),
    wf(
        "analysis",
        "Cases",
        "Show case",
        "kaizen_cases_show",
        &["id"],
        false,
        "detail",
    ),
    wf(
        "analysis",
        "Metrics",
        "Rebuild metrics index",
        "kaizen_metrics_index",
        &[],
        true,
        "toast",
    ),
    wf(
        "analysis",
        "Retro",
        "Analyze retro",
        "kaizen_retro",
        &[],
        false,
        "cards",
    ),
    wf(
        "analysis",
        "Reviews",
        "Dismiss review",
        "kaizen_review_dismiss",
        &["id"],
        true,
        "toast",
    ),
    wf(
        "analysis",
        "Reviews",
        "List reviews",
        "kaizen_review_list",
        &[],
        false,
        "table",
    ),
    wf(
        "analysis",
        "Reviews",
        "Resolve review",
        "kaizen_review_resolve",
        &["id"],
        true,
        "toast",
    ),
    wf(
        "analysis",
        "Reviews",
        "Show review",
        "kaizen_review_show",
        &["id"],
        false,
        "detail",
    ),
    wf(
        "analysis",
        "Rules",
        "Create rule",
        "kaizen_rules_create",
        &["name", "filter", "action"],
        true,
        "detail",
    ),
    wf(
        "analysis",
        "Rules",
        "Disable rule",
        "kaizen_rules_disable",
        &["id"],
        true,
        "toast",
    ),
    wf(
        "analysis",
        "Rules",
        "Enable rule",
        "kaizen_rules_enable",
        &["id"],
        true,
        "toast",
    ),
    wf(
        "analysis",
        "Rules",
        "List rules",
        "kaizen_rules_list",
        &[],
        false,
        "table",
    ),
    wf(
        "analysis",
        "Rules",
        "Run rules",
        "kaizen_rules_run",
        &[],
        true,
        "cards",
    ),
];
