// SPDX-License-Identifier: AGPL-3.0-or-later
pub mod cli;
pub mod doctor;
pub mod exp;
pub mod fmt;
pub mod gc;
pub mod guidance;
pub mod ingest;
pub mod init;
pub mod insights;
pub mod metrics;
pub mod proxy;
pub mod retro;
pub mod scope;
pub mod sync;
pub mod telemetry;
