#!/usr/bin/env bash
# Renders Homebrew Formula/kaizen-cli.rb with real sha256 from dist/*.sha256
# (same layout as the Release workflow after `Package`).
#
# Usage: render-homebrew-tap-formula.sh <VERSION_SEMVER> <DIST_DIR>
# Example: ./scripts/render-homebrew-tap-formula.sh 0.1.0 ./dist
set -euo pipefail

VERSION="${1:-}"
DIST="${2:-}"

if [[ -z "$VERSION" || -z "$DIST" ]]; then
  echo "usage: $0 <version> <dist_dir>" >&2
  exit 1
fi

read_sha() {
  local triple="$1"
  local f="${DIST}/kaizen-v${VERSION}-${triple}.tar.gz.sha256"
  if [[ ! -f "$f" ]]; then
    echo "missing: $f" >&2
    exit 1
  fi
  head -1 "$f" | awk '{print $1}'
}

AARCH64_DARWIN="$(read_sha aarch64-apple-darwin)"
X64_DARWIN="$(read_sha x86_64-apple-darwin)"
AARCH64_LINUX="$(read_sha aarch64-unknown-linux-gnu)"
X64_LINUX="$(read_sha x86_64-unknown-linux-gnu)"

cat <<RUBY
# frozen_string_literal: true
# Generated by scripts/render-homebrew-tap-formula.sh — do not edit shas by hand.

class KaizenCli < Formula
  desc "Distributable agent observability: sessions, retros, and repo-level improvement for coding agents"
  homepage "https://github.com/marquesds/kaizen"
  version "${VERSION}"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/marquesds/kaizen/releases/download/v${VERSION}/kaizen-v${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${AARCH64_DARWIN}"
    end
    on_intel do
      url "https://github.com/marquesds/kaizen/releases/download/v${VERSION}/kaizen-v${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "${X64_DARWIN}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marquesds/kaizen/releases/download/v${VERSION}/kaizen-v${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${AARCH64_LINUX}"
    end
    on_intel do
      url "https://github.com/marquesds/kaizen/releases/download/v${VERSION}/kaizen-v${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${X64_LINUX}"
    end
  end

  def install
    bin.install Dir.glob("kaizen-*/kaizen").first
  end

  test do
    system bin/"kaizen", "--version"
  end
end
RUBY
